### ISSUE TITLE
Update info page

### ISSUE THREAD

**Issue by ProxyScrape** [ProxyScrape/proxyscrape-proxy-checker#11]
Make the [info page](https://i.imgur.com/2PQacPw.png) similar to the license page in terms of size & add a close button. (make sure there is still enough padding on the bottom, and the padding on top should be the same aswell.
Replace with our logo: https://i.imgur.com/Fjw6NT3.pngx
Move link to the correct position: https://i.imgur.com/UL6n8vG.png
Add a link to our twitter, linkedin, and website in here: https://i.imgur.com/bj9mAkl.png
https://www.linkedin.com/company/proxyscrape/
https://twitter.com/proxyscrape_off

**Comment by bohdev95** [comment]
fixed
